services:
  express:
    build:
      context: .
      dockerfile: Dockerfile.express
      target: development

    env_file:
      - .env

    ports: ["3000:3000"]

    volumes:
      - node_modules:/usr/src/app/node_modules

    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app
          initial_sync: true
          ignore: ["node_modules/", ".git/"]

        - action: rebuild
          path: package.json

        - action: restart
          path: ./server.js
          target: /usr/src/app/
          initial_sync: true

        - action: restart
          path: ./src/
          target: /usr/src/app/
          initial_sync: true

    networks: [db]

    depends_on: [mongodb]

  mongo-express:
    image: mongo-express

    ports: [8081:8081]

    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_ROOT_USER:-admin}:${MONGODB_ROOT_PASSWORD:-adminpassword}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_ROOT_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_ROOT_PASSWORD:-adminpassword}

    networks: [db]

    depends_on: [mongodb]
  mongodb:
    image: mongo:latest

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-adminpassword}
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-base}
      MONGODB_DB: ${MONGODB_DB:-base}
      MONGODB_USER: ${MONGODB_USER:-user}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-password}

    volumes:
      - mongodbdata:/data/db
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro

    networks: [db]

    command: mongod --quiet --logpath /dev/null

volumes:
  mongodbdata:
  node_modules:

networks:
  db:
