services:
  express:
    build:
      context: .
      dockerfile: Dockerfile.express
      target: development

    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

    ports: ["3000:3000"]

    volumes:
      - node_modules:/usr/src/app/node_modules

    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app
          initial_sync: true
          ignore: ["node_modules/", ".git/"]

        - action: rebuild
          path: package.json

        - action: restart
          path: ./server.js
          target: /usr/src/app
          initial_sync: true

    networks: [db]

    depends_on: [mongodb]

  mongodb:
    image: mongo:latest

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    volumes:
      - mongodbdata:/data/db

    ports: ["27017:27017"]

    networks: [db]

volumes:
  mongodbdata:
  node_modules:

networks:
  db:
