services:
  express:
    build:
      context: .
      dockerfile: Dockerfile.express
      target: development

    env_file:
      - .env

    ports: ["3000:3000"]

    volumes:
      - node_modules:/usr/src/app/node_modules

    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app
          initial_sync: true
          ignore: ["node_modules/", ".git/"]

        - action: rebuild
          path: package.json

        - action: restart
          path: ./server.js
          target: /usr/src/app/server.js
          initial_sync: true

    networks: [db]

    depends_on: [mongodb]

  mongodb:
    image: mongo:latest

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-bibliotheque}

    volumes:
      - mongodbdata:/data/db

    networks: [db]

    command: mongod --quiet --logpath /dev/null

volumes:
  mongodbdata:
  node_modules:

networks:
  db:
